// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"gitlab.ezrpro.in/godemo/global"
)

// Injectors from wire.go:

func InitServer() *global.Server {
	engine := global.NewGinEngine()
	server := global.NewServer(engine)
	return server
}
