// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/google/wire"
	"gitlab.ezrpro.in/godemo/global"
	"gitlab.ezrpro.in/godemo/internal/api"
	"gitlab.ezrpro.in/godemo/internal/api/handlers"
	"gitlab.ezrpro.in/godemo/internal/repo"
	"gitlab.ezrpro.in/godemo/internal/service"
)

// Injectors from wire.go:

func InitServer(app *global.Application) *global.Server {
	engine := global.NewGinEngine()
	testHandler := handlers.NewTestHandler()
	db := global.InitDB(app)
	iProjectRepo := repo.NewMysqlProjectRepo(db)
	iProjectService := service.NewProjectService(iProjectRepo)
	projectHandler := handlers.NewProjectHandler(iProjectService)
	syncProducer := global.InitSaramaKafkaProducer(app)
	iProducerRepo := repo.NewSaramaKafkaProducer(syncProducer)
	iProducerService := service.NewProducerService(iProducerRepo)
	producerHandler := handlers.NewProducerHandler(iProducerService)
	routers := api.NewRouters(testHandler, projectHandler, producerHandler)
	server := global.NewServer(engine, routers)
	return server
}

// wire.go:

// 开发过程 router->handler->service->repository
var ProviderRoutersSet = wire.NewSet(api.NewRouters, api.NewTestRouter, api.NewProjectRouter, api.NewProducerRouter)

var ProviderHandlersSet = wire.NewSet(handlers.NewTestHandler, handlers.NewProjectHandler, handlers.NewProducerHandler)

var ProviderServicesSet = wire.NewSet(service.NewProjectService, service.NewProducerService)

var ProviderReposSet = wire.NewSet(repo.NewMysqlProjectRepo, repo.NewSaramaKafkaProducer)
