// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/google/wire"
	"gitlab.ezrpro.in/godemo/global"
	"gitlab.ezrpro.in/godemo/internal/api"
	"gitlab.ezrpro.in/godemo/internal/api/handlers"
)

// Injectors from wire.go:

func InitServer() *global.Server {
	engine := global.NewGinEngine()
	pingHandler := handlers.NewPingHandler()
	routers := api.NewRouters(pingHandler)
	server := global.NewServer(engine, routers)
	return server
}

// wire.go:

// 开发过程 router->handler->service->repository
var ProviderRoutersSet = wire.NewSet(api.NewRouters, api.NewPingRouter)

var ProviderHandlersSet = wire.NewSet(handlers.NewPingHandler)

var ProviderServicesSet = wire.NewSet()

var ProviderReposSet = wire.NewSet()
